baseURL = 'https://tiwu.github.io/'
languageCode = 'en-us'
title = "TiWu's Pages"
theme = 'hugo-geekdoc'

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[params]
    # (Optional, default false) Enforce code blocks to always use the dark color theme.
    geekdocDarkModeCode = true
    geekdocRepo = 'https://github.com/tiwu/tiwu.github.io'
    geekdocEditPath = 'edit/master'
